wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path('wiki/<str:title>', views.render_entry, name="render_entry"),
    path("search/", views.search, name="search"),
    path("new/", views.new, name="new"),
    path("wiki/<str:entry>/edit/", views.edit, name="edit"),
    path("random/", views.random, name="random")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.utils.safestring import mark_safe
from django.urls import reverse
from django import forms

from . import util
from random import choice

class NewPageForm(forms.Form):

    page_title = forms.CharField(label="Page Title", widget=forms.TextInput(attrs={'placeholder':'What is the wiki page for?'}))
    markdown = forms.CharField(label="Contents", widget=forms.Textarea(attrs={'placeholder':'', 'style': "width:100%;"}))

class EditPageForm(forms.Form):

    markdown = forms.CharField(label="Contents", widget=forms.Textarea(attrs={'placeholder':'Enter the Markdown data for the page.', 'style': "width:100%;"}))
        

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def render_entry(request, title):
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "info": util.get_entry(title)
    })

def search(request):

    if request.method == 'POST':

        if info := util.get_entry(request.POST["q"]):   #If query directly matches a wiki page:
            return HttpResponseRedirect(reverse('wiki:render_entry', kwargs={'title': request.POST["q"]}))  #Redirects to the wiki page
        
        else:
            entries = [e for e in util.list_entries() if request.POST["q"].lower() in e.lower()]    #Contains any entry that contains the query as a substring
            if len(entries) < 1:
                entries.append("No results found.")

            return render(request, "encyclopedia/search.html", {
            "substring": request.POST["q"],
            "entries": entries
            })
        
def new(request):
 
    if request.method == 'POST':
        try:
            util.new_entry(request.POST["page_title"], request.POST["markdown"])
        except ValueError:
            form = NewPageForm(request.POST)
            form.add_error(None, f"An entry already exists for \"{request.POST['page_title']}.\"\n" +
                           "Please enter a different title for your page!")
            return render(request, "encyclopedia/newpage.html", {
            "form": form
        })
        else:
            return HttpResponseRedirect(reverse('wiki:index'))

    else:
        return render(request, "encyclopedia/newpage.html", {
            "form": NewPageForm()
        })
    
def edit(request, entry):

    if request.method == 'POST':
        print("test2")
        util.save_entry(entry, bytes(request.POST["markdown"], 'utf8')) #Returns the data to 'utf8', since it was recoded from utf-8 in get_entry. Prevents edited markdown from adding spaces.
        return HttpResponseRedirect(f'/wiki/{entry}')
    
    else:
        return render(request, "encyclopedia/edit.html", {
            "entry": entry,
            "form": EditPageForm(initial={'markdown': util.get_md_entry(entry)})
        })
    
def random(request):
    entry = choice(util.list_entries())
    return HttpResponseRedirect(f'/wiki/{entry}')



    

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create a Wiki Page
{% endblock %}


{% block body %}

    {% csrf_token %}
    <h1>Edit the "{{ entry }}" Wiki Page</h1>
    <form action=" {% url 'wiki:edit' entry %}" method="post">

        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit Edit">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki: {{ title }}
{% endblock %}

{% block body %}

    

    {% if info == None %}
        <h2>A wiki entry was not found for "{{ title }}".</h2>
    {% else %}
    <a href="/wiki/{{ title }}/edit">Edit this page</a>
        {{ info | safe }}
    {% endif %}

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="/wiki/{{ entry }}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        {% block style %}{% endblock %}
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="post"> 
                    
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new' %}">Create a New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create a Wiki Page
{% endblock %}


{% block body %}

    {% csrf_token %}
    <h1>Create a New Wiki Page</h1>
    <form action="{% url 'wiki:new' %}" method="post">

        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Page">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search the Wiki
{% endblock %}

{% block body %}
    <h1>Search results for {{ substring }}:</h1>
    <ul>
        {% for entry in entries %}
            {% if entry ==  'No results found.' %}
            <li>
                {{ entry }}
            </li>
            {% else %}
                <li>
                    <a href="/wiki/{{ entry }}">{{ entry }}</a>
                </li>
            {% endif %} 
        {% endfor %}
    </ul>

{% endblock %}